# Generated by cucumber-sinatra. (2014-10-06 14:38:22 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/name_that_researcher.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = NameThatResearcher

class NameThatResearcherWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  NameThatResearcherWorld.new
end
